apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app_name: mylocalservice
  name: mylocalservice
spec:
  ports:
    - name: port-80
      port: 80
      targetPort: 4000
  selector:
    app_name: mylocalservice
  type: ClusterIP
